# Generated by Django 3.2.7 on 2021-11-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('topic_id', models.IntegerField()),
            ],
        ),
    ]
